package hello;

import java.util.HashMap;
import java.util.LinkedList;

/**
 * Created by jelcz on 2016-10-12.
 */
public class Utils {
    MusicDao musicDao = new MusicDao();

    LinkedList<String> genresNamesStringList = new LinkedList<>();
    LinkedList<String> genresNamesList = new LinkedList<>();
    HashMap<String, Integer> genresNamesMap = new HashMap<>();
    LinkedList<GenreAssoc> genresNamesAssocList = new LinkedList<>();

    public void createGenreList(){

        fillGenresNamesList(genresNamesStringList);

        for(int i = 0; i < genresNamesStringList.size(); i++){
            musicDao.insertIntoGenres(i, genresNamesStringList.get(i));
            genresNamesList.add(i, genresNamesStringList.get(i));
            genresNamesMap.put(genresNamesStringList.get(i), i);
        }
    }

    public void createGenresAssocList(LinkedList<Genre> genres){

        fillGenresAssocList(genresNamesMap);
        for(int i = 0; i < genresNamesAssocList.size(); i++){
            musicDao.insertIntoGenresAssoc(i, genresNamesAssocList.get(i).getGenreAssocIdFrom(), genresNamesAssocList.get(i).getGenreAssocIdTo());
        }
    }

    public void createGenreTable(){
        musicDao.truncateTable("genres");
    }
    public void truncateGenreTable(){
        musicDao.truncateTable("genres");
    }


    public void createGenresAssocTable(){
        musicDao.truncateTable("genresAssoc");
    }
    public void truncateGenresAssocTable(){
        musicDao.truncateTable("genresAssoc");
    }
    public void truncateTracksTable(){
        musicDao.truncateTable("songs");
    }


    private void fillGenresAssocList(HashMap<String, Integer> genresNamesMap) {
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("classical"), genresNamesMap.get("progressive rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("classical"), genresNamesMap.get("neoclassical metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("classical"), genresNamesMap.get("avantgarde")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("gospel"), genresNamesMap.get("doo wop")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("hawaiian  folk"), genresNamesMap.get("surf")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("mexican folk"), genresNamesMap.get("surf")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("spirituals"), genresNamesMap.get("blues")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("work songs"), genresNamesMap.get("blues")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("classical"), genresNamesMap.get("art rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("hymns"), genresNamesMap.get("appalachian folk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("angloceltic folk"), genresNamesMap.get("appalachian folk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("angloceltic folk"), genresNamesMap.get("western music")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("angloceltic folk"), genresNamesMap.get("bluegrass")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("angloceltic folk"), genresNamesMap.get("neofolk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("angloceltic folk"), genresNamesMap.get("blues")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("angloceltic folk"), genresNamesMap.get("electric folk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("western music"), genresNamesMap.get("country")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("appalachian folk"), genresNamesMap.get("bluegrass")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("appalachian folk"), genresNamesMap.get("neofolk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("appalachian folk"), genresNamesMap.get("folk rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("blues"), genresNamesMap.get("jump blues")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("bluegrass"), genresNamesMap.get("country")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("blues"), genresNamesMap.get("skiffle")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("blues"), genresNamesMap.get("punk blues")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("blues"), genresNamesMap.get("boogie woogie")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("blues"), genresNamesMap.get("electric blues")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("angloceltic folk"), genresNamesMap.get("roots rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("western music"), genresNamesMap.get("western swing")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("blues"), genresNamesMap.get("roots rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("angloceltic folk"), genresNamesMap.get("country folk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("jazz"), genresNamesMap.get("krautrock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("jazz"), genresNamesMap.get("skiffle")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("boogie woogie"), genresNamesMap.get("rockabilly")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("boogie woogie"), genresNamesMap.get("boogie rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("country"), genresNamesMap.get("rock  roll")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("country"), genresNamesMap.get("cowpunk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("country"), genresNamesMap.get("country rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("country"), genresNamesMap.get("country folk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("country"), genresNamesMap.get("skiffle")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("country"), genresNamesMap.get("roots rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("country"), genresNamesMap.get("country pop")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("country"), genresNamesMap.get("rockabilly")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("country"), genresNamesMap.get("heartland rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("big band"), genresNamesMap.get("jump blues")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("swing"), genresNamesMap.get("western swing")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("electric blues"), genresNamesMap.get("blues rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("western swing"), genresNamesMap.get("rockabilly")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("jump blues"), genresNamesMap.get("rhythm  blues")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("avantgarde"), genresNamesMap.get("progressive rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("avantgarde"), genresNamesMap.get("glam rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("avantgarde"), genresNamesMap.get("experimental rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("avantgarde"), genresNamesMap.get("industrial")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("avantgarde"), genresNamesMap.get("no wave")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("avantgarde"), genresNamesMap.get("experimental metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("rhythm  blues"), genresNamesMap.get("doo wop")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("rhythm  blues"), genresNamesMap.get("rock  roll")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("rock  roll"), genresNamesMap.get("funk rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("rock  roll"), genresNamesMap.get("garage rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("rock  roll"), genresNamesMap.get("surf")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("rock  roll"), genresNamesMap.get("beat music")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("rock  roll"), genresNamesMap.get("rockabilly")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("rock  roll"), genresNamesMap.get("blues rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("rock  roll"), genresNamesMap.get("heartland rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("rockabilly"), genresNamesMap.get("psychobilly")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("skiffle"), genresNamesMap.get("beat music")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("doo wop"), genresNamesMap.get("beat music")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("doo wop"), genresNamesMap.get("surf")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("ska"), genresNamesMap.get("2 tone")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("beat music"), genresNamesMap.get("rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("surf"), genresNamesMap.get("pop punk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("beat music"), genresNamesMap.get("folk rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("garage rock"), genresNamesMap.get("hard rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("blues rock"), genresNamesMap.get("heavy metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("blues rock"), genresNamesMap.get("stoner rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("garage rock"), genresNamesMap.get("garage punk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("garage rock"), genresNamesMap.get("indie rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("blues rock"), genresNamesMap.get("hard rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("blues rock"), genresNamesMap.get("psychedelic rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("blues rock"), genresNamesMap.get("boogie rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("folk rock"), genresNamesMap.get("psychedelic rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("drone"), genresNamesMap.get("industrial")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("folk rock"), genresNamesMap.get("soft rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("funk"), genresNamesMap.get("funk rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("folk rock"), genresNamesMap.get("electric folk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("beat music"), genresNamesMap.get("pop rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("garage rock"), genresNamesMap.get("rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("blues rock"), genresNamesMap.get("southern rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("drone"), genresNamesMap.get("drone metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("garage rock"), genresNamesMap.get("punk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("folk rock"), genresNamesMap.get("heartland rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("folk rock"), genresNamesMap.get("psychedelic folk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("psychedelic rock"), genresNamesMap.get("heavy metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("psychedelic rock"), genresNamesMap.get("art rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("psychedelic rock"), genresNamesMap.get("psychedelic folk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("psychedelic rock"), genresNamesMap.get("progressive rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("psychedelic rock"), genresNamesMap.get("glam rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("psychedelic rock"), genresNamesMap.get("stoner rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("experimental rock"), genresNamesMap.get("math rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("experimental rock"), genresNamesMap.get("art rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("experimental rock"), genresNamesMap.get("progressive rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("experimental rock"), genresNamesMap.get("post rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("roots rock"), genresNamesMap.get("southern rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("progressive rock"), genresNamesMap.get("symphonic rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("progressive rock"), genresNamesMap.get("progressive metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("progressive rock"), genresNamesMap.get("experimental metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("progressive rock"), genresNamesMap.get("krautrock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("hard rock"), genresNamesMap.get("boogie rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("krautrock"), genresNamesMap.get("new german wave")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("heavy metal"), genresNamesMap.get("symphonic metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("heavy metal"), genresNamesMap.get("experimental metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("art rock"), genresNamesMap.get("post punk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("art rock"), genresNamesMap.get("glam rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("art rock"), genresNamesMap.get("gothic rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("art rock"), genresNamesMap.get("art punk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("folk rock"), genresNamesMap.get("country rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("psychedelic rock"), genresNamesMap.get("space rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("psychedelic rock"), genresNamesMap.get("hard rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("experimental rock"), genresNamesMap.get("krautrock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("progressive rock"), genresNamesMap.get("space rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("hard rock"), genresNamesMap.get("rap rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("heavy metal"), genresNamesMap.get("stoner rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("heavy metal"), genresNamesMap.get("post metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("art rock"), genresNamesMap.get("space rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("psychedelic rock"), genresNamesMap.get("experimental rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("hard rock"), genresNamesMap.get("post grunge")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("heavy metal"), genresNamesMap.get("alternative metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("psychedelic rock"), genresNamesMap.get("krautrock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("heavy metal"), genresNamesMap.get("grunge")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("krautrock"), genresNamesMap.get("industrial")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("dub"), genresNamesMap.get("post punk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("krautrock"), genresNamesMap.get("art punk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("heavy metal"), genresNamesMap.get("rap metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("heavy metal"), genresNamesMap.get("doom metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("heavy metal"), genresNamesMap.get("speed metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("krautrock"), genresNamesMap.get("german electronic metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("heavy metal"), genresNamesMap.get("glam metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("heavy metal"), genresNamesMap.get("neoclassical metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("heavy metal"), genresNamesMap.get("funk metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("heavy metal"), genresNamesMap.get("progressive metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("heavy metal"), genresNamesMap.get("power metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("heavy metal"), genresNamesMap.get("extreme metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("disco"), genresNamesMap.get("new wave")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("symphonic rock"), genresNamesMap.get("symphonic metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("disco"), genresNamesMap.get("post punk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("country rock"), genresNamesMap.get("alternative country")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("pop rock"), genresNamesMap.get("glam rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("glam rock"), genresNamesMap.get("new wave")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("glam rock"), genresNamesMap.get("gothic rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("glam rock"), genresNamesMap.get("glam metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("doom metal"), genresNamesMap.get("drone metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("doom metal"), genresNamesMap.get("gothic metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("doom metal"), genresNamesMap.get("sludge metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("hip hop"), genresNamesMap.get("rap rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("punk"), genresNamesMap.get("alternative rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("punk"), genresNamesMap.get("2 tone")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("punk"), genresNamesMap.get("new wave")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("punk"), genresNamesMap.get("pop punk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("punk"), genresNamesMap.get("new german wave")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("punk"), genresNamesMap.get("punk blues")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("punk"), genresNamesMap.get("post punk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("punk"), genresNamesMap.get("art punk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("punk"), genresNamesMap.get("psychobilly")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("punk"), genresNamesMap.get("rapcore")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("punk"), genresNamesMap.get("garage punk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("funk rock"), genresNamesMap.get("funk metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("glam rock"), genresNamesMap.get("death rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("doom metal"), genresNamesMap.get("deathdoom")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("punk"), genresNamesMap.get("no wave")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("punk"), genresNamesMap.get("cowpunk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("punk"), genresNamesMap.get("hardcore punk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("new wave"), genresNamesMap.get("pop punk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("new wave"), genresNamesMap.get("2 tone")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("new wave"), genresNamesMap.get("indie rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("new wave"), genresNamesMap.get("cowpunk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("industrial"), genresNamesMap.get("industrial rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("industrial"), genresNamesMap.get("neofolk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("new wave"), genresNamesMap.get("gothic rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("industrial"), genresNamesMap.get("grindcore")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("new wave"), genresNamesMap.get("new german wave")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("new wave"), genresNamesMap.get("dark wave")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("post punk"), genresNamesMap.get("dark wave")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("2 tone"), genresNamesMap.get("ska punk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("post punk"), genresNamesMap.get("death rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("post punk"), genresNamesMap.get("industrial rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("post punk"), genresNamesMap.get("indie rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("post punk"), genresNamesMap.get("indie pop")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("hardcore punk"), genresNamesMap.get("dbeat")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("hardcore punk"), genresNamesMap.get("speed metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("industrial rock"), genresNamesMap.get("industrial metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("hardcore punk"), genresNamesMap.get("metalcore")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("hardcore punk"), genresNamesMap.get("rapcore")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("post punk"), genresNamesMap.get("shoegaze")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("hardcore punk"), genresNamesMap.get("grunge")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("hardcore punk"), genresNamesMap.get("industrial metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("post punk"), genresNamesMap.get("gothic rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("hardcore punk"), genresNamesMap.get("grindcore")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("noise rock"), genresNamesMap.get("shoegaze")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("post punk"), genresNamesMap.get("post rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("no wave"), genresNamesMap.get("noise rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("hardcore punk"), genresNamesMap.get("crust punk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("hardcore punk"), genresNamesMap.get("black metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("speed metal"), genresNamesMap.get("power metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("alternative rock"), genresNamesMap.get("alternative country")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("speed metal"), genresNamesMap.get("thrash metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("gothic rock"), genresNamesMap.get("gothabilly")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("gothic rock"), genresNamesMap.get("gothic metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("alternative rock"), genresNamesMap.get("indie rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("extreme metal"), genresNamesMap.get("grindcore")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("extreme metal"), genresNamesMap.get("crust punk")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("thrash metal"), genresNamesMap.get("industrial metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("hardcore punk"), genresNamesMap.get("sludge metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("hardcore punk"), genresNamesMap.get("thrashcore")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("alternative rock"), genresNamesMap.get("alternative metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("psychobilly"), genresNamesMap.get("gothabilly")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("hardcore punk"), genresNamesMap.get("emo")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("thrash metal"), genresNamesMap.get("metalcore")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("extreme metal"), genresNamesMap.get("dark metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("extreme metal"), genresNamesMap.get("experimental metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("thrash metal"), genresNamesMap.get("black metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("thrash metal"), genresNamesMap.get("groove metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("indie rock"), genresNamesMap.get("shoegaze")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("indie rock"), genresNamesMap.get("nu gaze")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("indie rock"), genresNamesMap.get("grunge")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("indie rock"), genresNamesMap.get("indie pop")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("thrash metal"), genresNamesMap.get("death metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("indie rock"), genresNamesMap.get("math rock")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("death metal"), genresNamesMap.get("black metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("death metal"), genresNamesMap.get("deathdoom")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("metalcore"), genresNamesMap.get("mathcore")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("rap rock"), genresNamesMap.get("rapcore")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("grunge"), genresNamesMap.get("post grunge")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("rap rock"), genresNamesMap.get("rap metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("rap metal"), genresNamesMap.get("nu metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("industrial metal"), genresNamesMap.get("german electronic metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("industrial metal"), genresNamesMap.get("nu metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("alternative metal"), genresNamesMap.get("nu metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("funk metal"), genresNamesMap.get("nu metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("techno"), genresNamesMap.get("german electronic metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("shoegaze"), genresNamesMap.get("post metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("shoegaze"), genresNamesMap.get("nu gaze")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("post rock"), genresNamesMap.get("post metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("math rock"), genresNamesMap.get("mathcore")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("groove metal"), genresNamesMap.get("german electronic metal")));
        genresNamesAssocList.add(new GenreAssoc(genresNamesMap.get("gothic metal"), genresNamesMap.get("dark metal")));
    }

    private void fillGenresNamesList(LinkedList<String> genresNamesList) {
        if(!genresNamesList.contains("classical")) genresNamesList.add("classical");
        if(!genresNamesList.contains("progressive rock")) genresNamesList.add("progressive rock");
        if(!genresNamesList.contains("classical")) genresNamesList.add("classical");
        if(!genresNamesList.contains("neoclassical metal")) genresNamesList.add("neoclassical metal");
        if(!genresNamesList.contains("classical")) genresNamesList.add("classical");
        if(!genresNamesList.contains("avantgarde")) genresNamesList.add("avantgarde");
        if(!genresNamesList.contains("gospel")) genresNamesList.add("gospel");
        if(!genresNamesList.contains("doo wop")) genresNamesList.add("doo wop");
        if(!genresNamesList.contains("hawaiian  folk")) genresNamesList.add("hawaiian  folk");
        if(!genresNamesList.contains("surf")) genresNamesList.add("surf");
        if(!genresNamesList.contains("mexican folk")) genresNamesList.add("mexican folk");
        if(!genresNamesList.contains("surf")) genresNamesList.add("surf");
        if(!genresNamesList.contains("spirituals")) genresNamesList.add("spirituals");
        if(!genresNamesList.contains("blues")) genresNamesList.add("blues");
        if(!genresNamesList.contains("work songs")) genresNamesList.add("work songs");
        if(!genresNamesList.contains("blues")) genresNamesList.add("blues");
        if(!genresNamesList.contains("classical")) genresNamesList.add("classical");
        if(!genresNamesList.contains("art rock")) genresNamesList.add("art rock");
        if(!genresNamesList.contains("hymns")) genresNamesList.add("hymns");
        if(!genresNamesList.contains("appalachian folk")) genresNamesList.add("appalachian folk");
        if(!genresNamesList.contains("angloceltic folk")) genresNamesList.add("angloceltic folk");
        if(!genresNamesList.contains("appalachian folk")) genresNamesList.add("appalachian folk");
        if(!genresNamesList.contains("angloceltic folk")) genresNamesList.add("angloceltic folk");
        if(!genresNamesList.contains("western music")) genresNamesList.add("western music");
        if(!genresNamesList.contains("angloceltic folk")) genresNamesList.add("angloceltic folk");
        if(!genresNamesList.contains("bluegrass")) genresNamesList.add("bluegrass");
        if(!genresNamesList.contains("angloceltic folk")) genresNamesList.add("angloceltic folk");
        if(!genresNamesList.contains("neofolk")) genresNamesList.add("neofolk");
        if(!genresNamesList.contains("angloceltic folk")) genresNamesList.add("angloceltic folk");
        if(!genresNamesList.contains("blues")) genresNamesList.add("blues");
        if(!genresNamesList.contains("angloceltic folk")) genresNamesList.add("angloceltic folk");
        if(!genresNamesList.contains("electric folk")) genresNamesList.add("electric folk");
        if(!genresNamesList.contains("western music")) genresNamesList.add("western music");
        if(!genresNamesList.contains("country")) genresNamesList.add("country");
        if(!genresNamesList.contains("appalachian folk")) genresNamesList.add("appalachian folk");
        if(!genresNamesList.contains("bluegrass")) genresNamesList.add("bluegrass");
        if(!genresNamesList.contains("appalachian folk")) genresNamesList.add("appalachian folk");
        if(!genresNamesList.contains("neofolk")) genresNamesList.add("neofolk");
        if(!genresNamesList.contains("appalachian folk")) genresNamesList.add("appalachian folk");
        if(!genresNamesList.contains("folk rock")) genresNamesList.add("folk rock");
        if(!genresNamesList.contains("blues")) genresNamesList.add("blues");
        if(!genresNamesList.contains("jump blues")) genresNamesList.add("jump blues");
        if(!genresNamesList.contains("bluegrass")) genresNamesList.add("bluegrass");
        if(!genresNamesList.contains("country")) genresNamesList.add("country");
        if(!genresNamesList.contains("blues")) genresNamesList.add("blues");
        if(!genresNamesList.contains("skiffle")) genresNamesList.add("skiffle");
        if(!genresNamesList.contains("blues")) genresNamesList.add("blues");
        if(!genresNamesList.contains("punk blues")) genresNamesList.add("punk blues");
        if(!genresNamesList.contains("blues")) genresNamesList.add("blues");
        if(!genresNamesList.contains("boogie woogie")) genresNamesList.add("boogie woogie");
        if(!genresNamesList.contains("blues")) genresNamesList.add("blues");
        if(!genresNamesList.contains("electric blues")) genresNamesList.add("electric blues");
        if(!genresNamesList.contains("angloceltic folk")) genresNamesList.add("angloceltic folk");
        if(!genresNamesList.contains("roots rock")) genresNamesList.add("roots rock");
        if(!genresNamesList.contains("western music")) genresNamesList.add("western music");
        if(!genresNamesList.contains("western swing")) genresNamesList.add("western swing");
        if(!genresNamesList.contains("blues")) genresNamesList.add("blues");
        if(!genresNamesList.contains("roots rock")) genresNamesList.add("roots rock");
        if(!genresNamesList.contains("angloceltic folk")) genresNamesList.add("angloceltic folk");
        if(!genresNamesList.contains("country folk")) genresNamesList.add("country folk");
        if(!genresNamesList.contains("jazz")) genresNamesList.add("jazz");
        if(!genresNamesList.contains("krautrock")) genresNamesList.add("krautrock");
        if(!genresNamesList.contains("jazz")) genresNamesList.add("jazz");
        if(!genresNamesList.contains("skiffle")) genresNamesList.add("skiffle");
        if(!genresNamesList.contains("boogie woogie")) genresNamesList.add("boogie woogie");
        if(!genresNamesList.contains("rockabilly")) genresNamesList.add("rockabilly");
        if(!genresNamesList.contains("boogie woogie")) genresNamesList.add("boogie woogie");
        if(!genresNamesList.contains("boogie rock")) genresNamesList.add("boogie rock");
        if(!genresNamesList.contains("country")) genresNamesList.add("country");
        if(!genresNamesList.contains("rock  roll")) genresNamesList.add("rock  roll");
        if(!genresNamesList.contains("country")) genresNamesList.add("country");
        if(!genresNamesList.contains("cowpunk")) genresNamesList.add("cowpunk");
        if(!genresNamesList.contains("country")) genresNamesList.add("country");
        if(!genresNamesList.contains("country rock")) genresNamesList.add("country rock");
        if(!genresNamesList.contains("country")) genresNamesList.add("country");
        if(!genresNamesList.contains("country folk")) genresNamesList.add("country folk");
        if(!genresNamesList.contains("country")) genresNamesList.add("country");
        if(!genresNamesList.contains("skiffle")) genresNamesList.add("skiffle");
        if(!genresNamesList.contains("country")) genresNamesList.add("country");
        if(!genresNamesList.contains("roots rock")) genresNamesList.add("roots rock");
        if(!genresNamesList.contains("country")) genresNamesList.add("country");
        if(!genresNamesList.contains("country pop")) genresNamesList.add("country pop");
        if(!genresNamesList.contains("country")) genresNamesList.add("country");
        if(!genresNamesList.contains("rockabilly")) genresNamesList.add("rockabilly");
        if(!genresNamesList.contains("country")) genresNamesList.add("country");
        if(!genresNamesList.contains("heartland rock")) genresNamesList.add("heartland rock");
        if(!genresNamesList.contains("big band")) genresNamesList.add("big band");
        if(!genresNamesList.contains("jump blues")) genresNamesList.add("jump blues");
        if(!genresNamesList.contains("swing")) genresNamesList.add("swing");
        if(!genresNamesList.contains("western swing")) genresNamesList.add("western swing");
        if(!genresNamesList.contains("electric blues")) genresNamesList.add("electric blues");
        if(!genresNamesList.contains("blues rock")) genresNamesList.add("blues rock");
        if(!genresNamesList.contains("western swing")) genresNamesList.add("western swing");
        if(!genresNamesList.contains("rockabilly")) genresNamesList.add("rockabilly");
        if(!genresNamesList.contains("jump blues")) genresNamesList.add("jump blues");
        if(!genresNamesList.contains("rhythm  blues")) genresNamesList.add("rhythm  blues");
        if(!genresNamesList.contains("avantgarde")) genresNamesList.add("avantgarde");
        if(!genresNamesList.contains("progressive rock")) genresNamesList.add("progressive rock");
        if(!genresNamesList.contains("avantgarde")) genresNamesList.add("avantgarde");
        if(!genresNamesList.contains("glam rock")) genresNamesList.add("glam rock");
        if(!genresNamesList.contains("avantgarde")) genresNamesList.add("avantgarde");
        if(!genresNamesList.contains("experimental rock")) genresNamesList.add("experimental rock");
        if(!genresNamesList.contains("avantgarde")) genresNamesList.add("avantgarde");
        if(!genresNamesList.contains("industrial")) genresNamesList.add("industrial");
        if(!genresNamesList.contains("avantgarde")) genresNamesList.add("avantgarde");
        if(!genresNamesList.contains("no wave")) genresNamesList.add("no wave");
        if(!genresNamesList.contains("avantgarde")) genresNamesList.add("avantgarde");
        if(!genresNamesList.contains("experimental metal")) genresNamesList.add("experimental metal");
        if(!genresNamesList.contains("rhythm  blues")) genresNamesList.add("rhythm  blues");
        if(!genresNamesList.contains("doo wop")) genresNamesList.add("doo wop");
        if(!genresNamesList.contains("rhythm  blues")) genresNamesList.add("rhythm  blues");
        if(!genresNamesList.contains("rock  roll")) genresNamesList.add("rock  roll");
        if(!genresNamesList.contains("rock  roll")) genresNamesList.add("rock  roll");
        if(!genresNamesList.contains("funk rock")) genresNamesList.add("funk rock");
        if(!genresNamesList.contains("rock  roll")) genresNamesList.add("rock  roll");
        if(!genresNamesList.contains("garage rock")) genresNamesList.add("garage rock");
        if(!genresNamesList.contains("rock  roll")) genresNamesList.add("rock  roll");
        if(!genresNamesList.contains("surf")) genresNamesList.add("surf");
        if(!genresNamesList.contains("rock  roll")) genresNamesList.add("rock  roll");
        if(!genresNamesList.contains("beat music")) genresNamesList.add("beat music");
        if(!genresNamesList.contains("rock  roll")) genresNamesList.add("rock  roll");
        if(!genresNamesList.contains("rockabilly")) genresNamesList.add("rockabilly");
        if(!genresNamesList.contains("rock  roll")) genresNamesList.add("rock  roll");
        if(!genresNamesList.contains("blues rock")) genresNamesList.add("blues rock");
        if(!genresNamesList.contains("rock  roll")) genresNamesList.add("rock  roll");
        if(!genresNamesList.contains("heartland rock")) genresNamesList.add("heartland rock");
        if(!genresNamesList.contains("rockabilly")) genresNamesList.add("rockabilly");
        if(!genresNamesList.contains("psychobilly")) genresNamesList.add("psychobilly");
        if(!genresNamesList.contains("skiffle")) genresNamesList.add("skiffle");
        if(!genresNamesList.contains("beat music")) genresNamesList.add("beat music");
        if(!genresNamesList.contains("doo wop")) genresNamesList.add("doo wop");
        if(!genresNamesList.contains("beat music")) genresNamesList.add("beat music");
        if(!genresNamesList.contains("doo wop")) genresNamesList.add("doo wop");
        if(!genresNamesList.contains("surf")) genresNamesList.add("surf");
        if(!genresNamesList.contains("ska")) genresNamesList.add("ska");
        if(!genresNamesList.contains("2 tone")) genresNamesList.add("2 tone");
        if(!genresNamesList.contains("beat music")) genresNamesList.add("beat music");
        if(!genresNamesList.contains("rock")) genresNamesList.add("rock");
        if(!genresNamesList.contains("surf")) genresNamesList.add("surf");
        if(!genresNamesList.contains("pop punk")) genresNamesList.add("pop punk");
        if(!genresNamesList.contains("beat music")) genresNamesList.add("beat music");
        if(!genresNamesList.contains("folk rock")) genresNamesList.add("folk rock");
        if(!genresNamesList.contains("garage rock")) genresNamesList.add("garage rock");
        if(!genresNamesList.contains("hard rock")) genresNamesList.add("hard rock");
        if(!genresNamesList.contains("blues rock")) genresNamesList.add("blues rock");
        if(!genresNamesList.contains("heavy metal")) genresNamesList.add("heavy metal");
        if(!genresNamesList.contains("blues rock")) genresNamesList.add("blues rock");
        if(!genresNamesList.contains("stoner rock")) genresNamesList.add("stoner rock");
        if(!genresNamesList.contains("garage rock")) genresNamesList.add("garage rock");
        if(!genresNamesList.contains("garage punk")) genresNamesList.add("garage punk");
        if(!genresNamesList.contains("garage rock")) genresNamesList.add("garage rock");
        if(!genresNamesList.contains("indie rock")) genresNamesList.add("indie rock");
        if(!genresNamesList.contains("blues rock")) genresNamesList.add("blues rock");
        if(!genresNamesList.contains("hard rock")) genresNamesList.add("hard rock");
        if(!genresNamesList.contains("blues rock")) genresNamesList.add("blues rock");
        if(!genresNamesList.contains("psychedelic rock")) genresNamesList.add("psychedelic rock");
        if(!genresNamesList.contains("blues rock")) genresNamesList.add("blues rock");
        if(!genresNamesList.contains("boogie rock")) genresNamesList.add("boogie rock");
        if(!genresNamesList.contains("folk rock")) genresNamesList.add("folk rock");
        if(!genresNamesList.contains("psychedelic rock")) genresNamesList.add("psychedelic rock");
        if(!genresNamesList.contains("drone")) genresNamesList.add("drone");
        if(!genresNamesList.contains("industrial")) genresNamesList.add("industrial");
        if(!genresNamesList.contains("folk rock")) genresNamesList.add("folk rock");
        if(!genresNamesList.contains("soft rock")) genresNamesList.add("soft rock");
        if(!genresNamesList.contains("funk")) genresNamesList.add("funk");
        if(!genresNamesList.contains("funk rock")) genresNamesList.add("funk rock");
        if(!genresNamesList.contains("folk rock")) genresNamesList.add("folk rock");
        if(!genresNamesList.contains("electric folk")) genresNamesList.add("electric folk");
        if(!genresNamesList.contains("beat music")) genresNamesList.add("beat music");
        if(!genresNamesList.contains("pop rock")) genresNamesList.add("pop rock");
        if(!genresNamesList.contains("garage rock")) genresNamesList.add("garage rock");
        if(!genresNamesList.contains("rock")) genresNamesList.add("rock");
        if(!genresNamesList.contains("blues rock")) genresNamesList.add("blues rock");
        if(!genresNamesList.contains("southern rock")) genresNamesList.add("southern rock");
        if(!genresNamesList.contains("drone")) genresNamesList.add("drone");
        if(!genresNamesList.contains("drone metal")) genresNamesList.add("drone metal");
        if(!genresNamesList.contains("garage rock")) genresNamesList.add("garage rock");
        if(!genresNamesList.contains("punk")) genresNamesList.add("punk");
        if(!genresNamesList.contains("folk rock")) genresNamesList.add("folk rock");
        if(!genresNamesList.contains("heartland rock")) genresNamesList.add("heartland rock");
        if(!genresNamesList.contains("folk rock")) genresNamesList.add("folk rock");
        if(!genresNamesList.contains("psychedelic folk")) genresNamesList.add("psychedelic folk");
        if(!genresNamesList.contains("psychedelic rock")) genresNamesList.add("psychedelic rock");
        if(!genresNamesList.contains("heavy metal")) genresNamesList.add("heavy metal");
        if(!genresNamesList.contains("psychedelic rock")) genresNamesList.add("psychedelic rock");
        if(!genresNamesList.contains("art rock")) genresNamesList.add("art rock");
        if(!genresNamesList.contains("psychedelic rock")) genresNamesList.add("psychedelic rock");
        if(!genresNamesList.contains("psychedelic folk")) genresNamesList.add("psychedelic folk");
        if(!genresNamesList.contains("psychedelic rock")) genresNamesList.add("psychedelic rock");
        if(!genresNamesList.contains("progressive rock")) genresNamesList.add("progressive rock");
        if(!genresNamesList.contains("psychedelic rock")) genresNamesList.add("psychedelic rock");
        if(!genresNamesList.contains("glam rock")) genresNamesList.add("glam rock");
        if(!genresNamesList.contains("psychedelic rock")) genresNamesList.add("psychedelic rock");
        if(!genresNamesList.contains("stoner rock")) genresNamesList.add("stoner rock");
        if(!genresNamesList.contains("experimental rock")) genresNamesList.add("experimental rock");
        if(!genresNamesList.contains("math rock")) genresNamesList.add("math rock");
        if(!genresNamesList.contains("experimental rock")) genresNamesList.add("experimental rock");
        if(!genresNamesList.contains("art rock")) genresNamesList.add("art rock");
        if(!genresNamesList.contains("experimental rock")) genresNamesList.add("experimental rock");
        if(!genresNamesList.contains("progressive rock")) genresNamesList.add("progressive rock");
        if(!genresNamesList.contains("experimental rock")) genresNamesList.add("experimental rock");
        if(!genresNamesList.contains("post rock")) genresNamesList.add("post rock");
        if(!genresNamesList.contains("roots rock")) genresNamesList.add("roots rock");
        if(!genresNamesList.contains("southern rock")) genresNamesList.add("southern rock");
        if(!genresNamesList.contains("progressive rock")) genresNamesList.add("progressive rock");
        if(!genresNamesList.contains("symphonic rock")) genresNamesList.add("symphonic rock");
        if(!genresNamesList.contains("progressive rock")) genresNamesList.add("progressive rock");
        if(!genresNamesList.contains("progressive metal")) genresNamesList.add("progressive metal");
        if(!genresNamesList.contains("progressive rock")) genresNamesList.add("progressive rock");
        if(!genresNamesList.contains("experimental metal")) genresNamesList.add("experimental metal");
        if(!genresNamesList.contains("progressive rock")) genresNamesList.add("progressive rock");
        if(!genresNamesList.contains("krautrock")) genresNamesList.add("krautrock");
        if(!genresNamesList.contains("hard rock")) genresNamesList.add("hard rock");
        if(!genresNamesList.contains("boogie rock")) genresNamesList.add("boogie rock");
        if(!genresNamesList.contains("krautrock")) genresNamesList.add("krautrock");
        if(!genresNamesList.contains("new german wave")) genresNamesList.add("new german wave");
        if(!genresNamesList.contains("heavy metal")) genresNamesList.add("heavy metal");
        if(!genresNamesList.contains("symphonic metal")) genresNamesList.add("symphonic metal");
        if(!genresNamesList.contains("heavy metal")) genresNamesList.add("heavy metal");
        if(!genresNamesList.contains("experimental metal")) genresNamesList.add("experimental metal");
        if(!genresNamesList.contains("art rock")) genresNamesList.add("art rock");
        if(!genresNamesList.contains("post punk")) genresNamesList.add("post punk");
        if(!genresNamesList.contains("art rock")) genresNamesList.add("art rock");
        if(!genresNamesList.contains("glam rock")) genresNamesList.add("glam rock");
        if(!genresNamesList.contains("art rock")) genresNamesList.add("art rock");
        if(!genresNamesList.contains("gothic rock")) genresNamesList.add("gothic rock");
        if(!genresNamesList.contains("art rock")) genresNamesList.add("art rock");
        if(!genresNamesList.contains("art punk")) genresNamesList.add("art punk");
        if(!genresNamesList.contains("folk rock")) genresNamesList.add("folk rock");
        if(!genresNamesList.contains("country rock")) genresNamesList.add("country rock");
        if(!genresNamesList.contains("psychedelic rock")) genresNamesList.add("psychedelic rock");
        if(!genresNamesList.contains("space rock")) genresNamesList.add("space rock");
        if(!genresNamesList.contains("psychedelic rock")) genresNamesList.add("psychedelic rock");
        if(!genresNamesList.contains("hard rock")) genresNamesList.add("hard rock");
        if(!genresNamesList.contains("experimental rock")) genresNamesList.add("experimental rock");
        if(!genresNamesList.contains("krautrock")) genresNamesList.add("krautrock");
        if(!genresNamesList.contains("progressive rock")) genresNamesList.add("progressive rock");
        if(!genresNamesList.contains("space rock")) genresNamesList.add("space rock");
        if(!genresNamesList.contains("hard rock")) genresNamesList.add("hard rock");
        if(!genresNamesList.contains("rap rock")) genresNamesList.add("rap rock");
        if(!genresNamesList.contains("heavy metal")) genresNamesList.add("heavy metal");
        if(!genresNamesList.contains("stoner rock")) genresNamesList.add("stoner rock");
        if(!genresNamesList.contains("heavy metal")) genresNamesList.add("heavy metal");
        if(!genresNamesList.contains("post metal")) genresNamesList.add("post metal");
        if(!genresNamesList.contains("art rock")) genresNamesList.add("art rock");
        if(!genresNamesList.contains("space rock")) genresNamesList.add("space rock");
        if(!genresNamesList.contains("psychedelic rock")) genresNamesList.add("psychedelic rock");
        if(!genresNamesList.contains("experimental rock")) genresNamesList.add("experimental rock");
        if(!genresNamesList.contains("hard rock")) genresNamesList.add("hard rock");
        if(!genresNamesList.contains("post grunge")) genresNamesList.add("post grunge");
        if(!genresNamesList.contains("heavy metal")) genresNamesList.add("heavy metal");
        if(!genresNamesList.contains("alternative metal")) genresNamesList.add("alternative metal");
        if(!genresNamesList.contains("psychedelic rock")) genresNamesList.add("psychedelic rock");
        if(!genresNamesList.contains("krautrock")) genresNamesList.add("krautrock");
        if(!genresNamesList.contains("heavy metal")) genresNamesList.add("heavy metal");
        if(!genresNamesList.contains("grunge")) genresNamesList.add("grunge");
        if(!genresNamesList.contains("krautrock")) genresNamesList.add("krautrock");
        if(!genresNamesList.contains("industrial")) genresNamesList.add("industrial");
        if(!genresNamesList.contains("dub")) genresNamesList.add("dub");
        if(!genresNamesList.contains("post punk")) genresNamesList.add("post punk");
        if(!genresNamesList.contains("krautrock")) genresNamesList.add("krautrock");
        if(!genresNamesList.contains("art punk")) genresNamesList.add("art punk");
        if(!genresNamesList.contains("heavy metal")) genresNamesList.add("heavy metal");
        if(!genresNamesList.contains("rap metal")) genresNamesList.add("rap metal");
        if(!genresNamesList.contains("heavy metal")) genresNamesList.add("heavy metal");
        if(!genresNamesList.contains("doom metal")) genresNamesList.add("doom metal");
        if(!genresNamesList.contains("heavy metal")) genresNamesList.add("heavy metal");
        if(!genresNamesList.contains("speed metal")) genresNamesList.add("speed metal");
        if(!genresNamesList.contains("krautrock")) genresNamesList.add("krautrock");
        if(!genresNamesList.contains("german electronic metal")) genresNamesList.add("german electronic metal");
        if(!genresNamesList.contains("heavy metal")) genresNamesList.add("heavy metal");
        if(!genresNamesList.contains("glam metal")) genresNamesList.add("glam metal");
        if(!genresNamesList.contains("heavy metal")) genresNamesList.add("heavy metal");
        if(!genresNamesList.contains("neoclassical metal")) genresNamesList.add("neoclassical metal");
        if(!genresNamesList.contains("heavy metal")) genresNamesList.add("heavy metal");
        if(!genresNamesList.contains("funk metal")) genresNamesList.add("funk metal");
        if(!genresNamesList.contains("heavy metal")) genresNamesList.add("heavy metal");
        if(!genresNamesList.contains("progressive metal")) genresNamesList.add("progressive metal");
        if(!genresNamesList.contains("heavy metal")) genresNamesList.add("heavy metal");
        if(!genresNamesList.contains("power metal")) genresNamesList.add("power metal");
        if(!genresNamesList.contains("heavy metal")) genresNamesList.add("heavy metal");
        if(!genresNamesList.contains("extreme metal")) genresNamesList.add("extreme metal");
        if(!genresNamesList.contains("disco")) genresNamesList.add("disco");
        if(!genresNamesList.contains("new wave")) genresNamesList.add("new wave");
        if(!genresNamesList.contains("symphonic rock")) genresNamesList.add("symphonic rock");
        if(!genresNamesList.contains("symphonic metal")) genresNamesList.add("symphonic metal");
        if(!genresNamesList.contains("disco")) genresNamesList.add("disco");
        if(!genresNamesList.contains("post punk")) genresNamesList.add("post punk");
        if(!genresNamesList.contains("country rock")) genresNamesList.add("country rock");
        if(!genresNamesList.contains("alternative country")) genresNamesList.add("alternative country");
        if(!genresNamesList.contains("pop rock")) genresNamesList.add("pop rock");
        if(!genresNamesList.contains("glam rock")) genresNamesList.add("glam rock");
        if(!genresNamesList.contains("glam rock")) genresNamesList.add("glam rock");
        if(!genresNamesList.contains("new wave")) genresNamesList.add("new wave");
        if(!genresNamesList.contains("glam rock")) genresNamesList.add("glam rock");
        if(!genresNamesList.contains("gothic rock")) genresNamesList.add("gothic rock");
        if(!genresNamesList.contains("glam rock")) genresNamesList.add("glam rock");
        if(!genresNamesList.contains("glam metal")) genresNamesList.add("glam metal");
        if(!genresNamesList.contains("doom metal")) genresNamesList.add("doom metal");
        if(!genresNamesList.contains("drone metal")) genresNamesList.add("drone metal");
        if(!genresNamesList.contains("doom metal")) genresNamesList.add("doom metal");
        if(!genresNamesList.contains("gothic metal")) genresNamesList.add("gothic metal");
        if(!genresNamesList.contains("doom metal")) genresNamesList.add("doom metal");
        if(!genresNamesList.contains("sludge metal")) genresNamesList.add("sludge metal");
        if(!genresNamesList.contains("hip hop")) genresNamesList.add("hip hop");
        if(!genresNamesList.contains("rap rock")) genresNamesList.add("rap rock");
        if(!genresNamesList.contains("punk")) genresNamesList.add("punk");
        if(!genresNamesList.contains("alternative rock")) genresNamesList.add("alternative rock");
        if(!genresNamesList.contains("punk")) genresNamesList.add("punk");
        if(!genresNamesList.contains("2 tone")) genresNamesList.add("2 tone");
        if(!genresNamesList.contains("punk")) genresNamesList.add("punk");
        if(!genresNamesList.contains("new wave")) genresNamesList.add("new wave");
        if(!genresNamesList.contains("punk")) genresNamesList.add("punk");
        if(!genresNamesList.contains("pop punk")) genresNamesList.add("pop punk");
        if(!genresNamesList.contains("punk")) genresNamesList.add("punk");
        if(!genresNamesList.contains("new german wave")) genresNamesList.add("new german wave");
        if(!genresNamesList.contains("punk")) genresNamesList.add("punk");
        if(!genresNamesList.contains("punk blues")) genresNamesList.add("punk blues");
        if(!genresNamesList.contains("punk")) genresNamesList.add("punk");
        if(!genresNamesList.contains("post punk")) genresNamesList.add("post punk");
        if(!genresNamesList.contains("punk")) genresNamesList.add("punk");
        if(!genresNamesList.contains("art punk")) genresNamesList.add("art punk");
        if(!genresNamesList.contains("punk")) genresNamesList.add("punk");
        if(!genresNamesList.contains("psychobilly")) genresNamesList.add("psychobilly");
        if(!genresNamesList.contains("punk")) genresNamesList.add("punk");
        if(!genresNamesList.contains("rapcore")) genresNamesList.add("rapcore");
        if(!genresNamesList.contains("punk")) genresNamesList.add("punk");
        if(!genresNamesList.contains("garage punk")) genresNamesList.add("garage punk");
        if(!genresNamesList.contains("funk rock")) genresNamesList.add("funk rock");
        if(!genresNamesList.contains("funk metal")) genresNamesList.add("funk metal");
        if(!genresNamesList.contains("glam rock")) genresNamesList.add("glam rock");
        if(!genresNamesList.contains("death rock")) genresNamesList.add("death rock");
        if(!genresNamesList.contains("doom metal")) genresNamesList.add("doom metal");
        if(!genresNamesList.contains("deathdoom")) genresNamesList.add("deathdoom");
        if(!genresNamesList.contains("punk")) genresNamesList.add("punk");
        if(!genresNamesList.contains("no wave")) genresNamesList.add("no wave");
        if(!genresNamesList.contains("punk")) genresNamesList.add("punk");
        if(!genresNamesList.contains("cowpunk")) genresNamesList.add("cowpunk");
        if(!genresNamesList.contains("punk")) genresNamesList.add("punk");
        if(!genresNamesList.contains("hardcore punk")) genresNamesList.add("hardcore punk");
        if(!genresNamesList.contains("new wave")) genresNamesList.add("new wave");
        if(!genresNamesList.contains("pop punk")) genresNamesList.add("pop punk");
        if(!genresNamesList.contains("new wave")) genresNamesList.add("new wave");
        if(!genresNamesList.contains("2 tone")) genresNamesList.add("2 tone");
        if(!genresNamesList.contains("new wave")) genresNamesList.add("new wave");
        if(!genresNamesList.contains("indie rock")) genresNamesList.add("indie rock");
        if(!genresNamesList.contains("new wave")) genresNamesList.add("new wave");
        if(!genresNamesList.contains("cowpunk")) genresNamesList.add("cowpunk");
        if(!genresNamesList.contains("industrial")) genresNamesList.add("industrial");
        if(!genresNamesList.contains("industrial rock")) genresNamesList.add("industrial rock");
        if(!genresNamesList.contains("industrial")) genresNamesList.add("industrial");
        if(!genresNamesList.contains("neofolk")) genresNamesList.add("neofolk");
        if(!genresNamesList.contains("new wave")) genresNamesList.add("new wave");
        if(!genresNamesList.contains("gothic rock")) genresNamesList.add("gothic rock");
        if(!genresNamesList.contains("industrial")) genresNamesList.add("industrial");
        if(!genresNamesList.contains("grindcore")) genresNamesList.add("grindcore");
        if(!genresNamesList.contains("new wave")) genresNamesList.add("new wave");
        if(!genresNamesList.contains("new german wave")) genresNamesList.add("new german wave");
        if(!genresNamesList.contains("new wave")) genresNamesList.add("new wave");
        if(!genresNamesList.contains("dark wave")) genresNamesList.add("dark wave");
        if(!genresNamesList.contains("post punk")) genresNamesList.add("post punk");
        if(!genresNamesList.contains("dark wave")) genresNamesList.add("dark wave");
        if(!genresNamesList.contains("2 tone")) genresNamesList.add("2 tone");
        if(!genresNamesList.contains("ska punk")) genresNamesList.add("ska punk");
        if(!genresNamesList.contains("post punk")) genresNamesList.add("post punk");
        if(!genresNamesList.contains("death rock")) genresNamesList.add("death rock");
        if(!genresNamesList.contains("post punk")) genresNamesList.add("post punk");
        if(!genresNamesList.contains("industrial rock")) genresNamesList.add("industrial rock");
        if(!genresNamesList.contains("post punk")) genresNamesList.add("post punk");
        if(!genresNamesList.contains("indie rock")) genresNamesList.add("indie rock");
        if(!genresNamesList.contains("post punk")) genresNamesList.add("post punk");
        if(!genresNamesList.contains("indie pop")) genresNamesList.add("indie pop");
        if(!genresNamesList.contains("hardcore punk")) genresNamesList.add("hardcore punk");
        if(!genresNamesList.contains("dbeat")) genresNamesList.add("dbeat");
        if(!genresNamesList.contains("hardcore punk")) genresNamesList.add("hardcore punk");
        if(!genresNamesList.contains("speed metal")) genresNamesList.add("speed metal");
        if(!genresNamesList.contains("industrial rock")) genresNamesList.add("industrial rock");
        if(!genresNamesList.contains("industrial metal")) genresNamesList.add("industrial metal");
        if(!genresNamesList.contains("hardcore punk")) genresNamesList.add("hardcore punk");
        if(!genresNamesList.contains("metalcore")) genresNamesList.add("metalcore");
        if(!genresNamesList.contains("hardcore punk")) genresNamesList.add("hardcore punk");
        if(!genresNamesList.contains("rapcore")) genresNamesList.add("rapcore");
        if(!genresNamesList.contains("post punk")) genresNamesList.add("post punk");
        if(!genresNamesList.contains("shoegaze")) genresNamesList.add("shoegaze");
        if(!genresNamesList.contains("hardcore punk")) genresNamesList.add("hardcore punk");
        if(!genresNamesList.contains("grunge")) genresNamesList.add("grunge");
        if(!genresNamesList.contains("hardcore punk")) genresNamesList.add("hardcore punk");
        if(!genresNamesList.contains("industrial metal")) genresNamesList.add("industrial metal");
        if(!genresNamesList.contains("post punk")) genresNamesList.add("post punk");
        if(!genresNamesList.contains("gothic rock")) genresNamesList.add("gothic rock");
        if(!genresNamesList.contains("hardcore punk")) genresNamesList.add("hardcore punk");
        if(!genresNamesList.contains("grindcore")) genresNamesList.add("grindcore");
        if(!genresNamesList.contains("noise rock")) genresNamesList.add("noise rock");
        if(!genresNamesList.contains("shoegaze")) genresNamesList.add("shoegaze");
        if(!genresNamesList.contains("post punk")) genresNamesList.add("post punk");
        if(!genresNamesList.contains("post rock")) genresNamesList.add("post rock");
        if(!genresNamesList.contains("no wave")) genresNamesList.add("no wave");
        if(!genresNamesList.contains("noise rock")) genresNamesList.add("noise rock");
        if(!genresNamesList.contains("hardcore punk")) genresNamesList.add("hardcore punk");
        if(!genresNamesList.contains("crust punk")) genresNamesList.add("crust punk");
        if(!genresNamesList.contains("hardcore punk")) genresNamesList.add("hardcore punk");
        if(!genresNamesList.contains("black metal")) genresNamesList.add("black metal");
        if(!genresNamesList.contains("speed metal")) genresNamesList.add("speed metal");
        if(!genresNamesList.contains("power metal")) genresNamesList.add("power metal");
        if(!genresNamesList.contains("alternative rock")) genresNamesList.add("alternative rock");
        if(!genresNamesList.contains("alternative country")) genresNamesList.add("alternative country");
        if(!genresNamesList.contains("speed metal")) genresNamesList.add("speed metal");
        if(!genresNamesList.contains("thrash metal")) genresNamesList.add("thrash metal");
        if(!genresNamesList.contains("gothic rock")) genresNamesList.add("gothic rock");
        if(!genresNamesList.contains("gothabilly")) genresNamesList.add("gothabilly");
        if(!genresNamesList.contains("gothic rock")) genresNamesList.add("gothic rock");
        if(!genresNamesList.contains("gothic metal")) genresNamesList.add("gothic metal");
        if(!genresNamesList.contains("alternative rock")) genresNamesList.add("alternative rock");
        if(!genresNamesList.contains("indie rock")) genresNamesList.add("indie rock");
        if(!genresNamesList.contains("extreme metal")) genresNamesList.add("extreme metal");
        if(!genresNamesList.contains("grindcore")) genresNamesList.add("grindcore");
        if(!genresNamesList.contains("extreme metal")) genresNamesList.add("extreme metal");
        if(!genresNamesList.contains("crust punk")) genresNamesList.add("crust punk");
        if(!genresNamesList.contains("thrash metal")) genresNamesList.add("thrash metal");
        if(!genresNamesList.contains("industrial metal")) genresNamesList.add("industrial metal");
        if(!genresNamesList.contains("hardcore punk")) genresNamesList.add("hardcore punk");
        if(!genresNamesList.contains("sludge metal")) genresNamesList.add("sludge metal");
        if(!genresNamesList.contains("hardcore punk")) genresNamesList.add("hardcore punk");
        if(!genresNamesList.contains("thrashcore")) genresNamesList.add("thrashcore");
        if(!genresNamesList.contains("alternative rock")) genresNamesList.add("alternative rock");
        if(!genresNamesList.contains("alternative metal")) genresNamesList.add("alternative metal");
        if(!genresNamesList.contains("psychobilly")) genresNamesList.add("psychobilly");
        if(!genresNamesList.contains("gothabilly")) genresNamesList.add("gothabilly");
        if(!genresNamesList.contains("hardcore punk")) genresNamesList.add("hardcore punk");
        if(!genresNamesList.contains("emo")) genresNamesList.add("emo");
        if(!genresNamesList.contains("thrash metal")) genresNamesList.add("thrash metal");
        if(!genresNamesList.contains("metalcore")) genresNamesList.add("metalcore");
        if(!genresNamesList.contains("extreme metal")) genresNamesList.add("extreme metal");
        if(!genresNamesList.contains("dark metal")) genresNamesList.add("dark metal");
        if(!genresNamesList.contains("extreme metal")) genresNamesList.add("extreme metal");
        if(!genresNamesList.contains("experimental metal")) genresNamesList.add("experimental metal");
        if(!genresNamesList.contains("thrash metal")) genresNamesList.add("thrash metal");
        if(!genresNamesList.contains("black metal")) genresNamesList.add("black metal");
        if(!genresNamesList.contains("thrash metal")) genresNamesList.add("thrash metal");
        if(!genresNamesList.contains("groove metal")) genresNamesList.add("groove metal");
        if(!genresNamesList.contains("indie rock")) genresNamesList.add("indie rock");
        if(!genresNamesList.contains("shoegaze")) genresNamesList.add("shoegaze");
        if(!genresNamesList.contains("indie rock")) genresNamesList.add("indie rock");
        if(!genresNamesList.contains("nu gaze")) genresNamesList.add("nu gaze");
        if(!genresNamesList.contains("indie rock")) genresNamesList.add("indie rock");
        if(!genresNamesList.contains("grunge")) genresNamesList.add("grunge");
        if(!genresNamesList.contains("indie rock")) genresNamesList.add("indie rock");
        if(!genresNamesList.contains("indie pop")) genresNamesList.add("indie pop");
        if(!genresNamesList.contains("thrash metal")) genresNamesList.add("thrash metal");
        if(!genresNamesList.contains("death metal")) genresNamesList.add("death metal");
        if(!genresNamesList.contains("indie rock")) genresNamesList.add("indie rock");
        if(!genresNamesList.contains("math rock")) genresNamesList.add("math rock");
        if(!genresNamesList.contains("death metal")) genresNamesList.add("death metal");
        if(!genresNamesList.contains("black metal")) genresNamesList.add("black metal");
        if(!genresNamesList.contains("death metal")) genresNamesList.add("death metal");
        if(!genresNamesList.contains("deathdoom")) genresNamesList.add("deathdoom");
        if(!genresNamesList.contains("metalcore")) genresNamesList.add("metalcore");
        if(!genresNamesList.contains("mathcore")) genresNamesList.add("mathcore");
        if(!genresNamesList.contains("rap rock")) genresNamesList.add("rap rock");
        if(!genresNamesList.contains("rapcore")) genresNamesList.add("rapcore");
        if(!genresNamesList.contains("grunge")) genresNamesList.add("grunge");
        if(!genresNamesList.contains("post grunge")) genresNamesList.add("post grunge");
        if(!genresNamesList.contains("rap rock")) genresNamesList.add("rap rock");
        if(!genresNamesList.contains("rap metal")) genresNamesList.add("rap metal");
        if(!genresNamesList.contains("rap metal")) genresNamesList.add("rap metal");
        if(!genresNamesList.contains("nu metal")) genresNamesList.add("nu metal");
        if(!genresNamesList.contains("industrial metal")) genresNamesList.add("industrial metal");
        if(!genresNamesList.contains("german electronic metal")) genresNamesList.add("german electronic metal");
        if(!genresNamesList.contains("industrial metal")) genresNamesList.add("industrial metal");
        if(!genresNamesList.contains("nu metal")) genresNamesList.add("nu metal");
        if(!genresNamesList.contains("alternative metal")) genresNamesList.add("alternative metal");
        if(!genresNamesList.contains("nu metal")) genresNamesList.add("nu metal");
        if(!genresNamesList.contains("funk metal")) genresNamesList.add("funk metal");
        if(!genresNamesList.contains("nu metal")) genresNamesList.add("nu metal");
        if(!genresNamesList.contains("techno")) genresNamesList.add("techno");
        if(!genresNamesList.contains("german electronic metal")) genresNamesList.add("german electronic metal");
        if(!genresNamesList.contains("shoegaze")) genresNamesList.add("shoegaze");
        if(!genresNamesList.contains("post metal")) genresNamesList.add("post metal");
        if(!genresNamesList.contains("shoegaze")) genresNamesList.add("shoegaze");
        if(!genresNamesList.contains("nu gaze")) genresNamesList.add("nu gaze");
        if(!genresNamesList.contains("post rock")) genresNamesList.add("post rock");
        if(!genresNamesList.contains("post metal")) genresNamesList.add("post metal");
        if(!genresNamesList.contains("math rock")) genresNamesList.add("math rock");
        if(!genresNamesList.contains("mathcore")) genresNamesList.add("mathcore");
        if(!genresNamesList.contains("groove metal")) genresNamesList.add("groove metal");
        if(!genresNamesList.contains("german electronic metal")) genresNamesList.add("german electronic metal");
        if(!genresNamesList.contains("gothic metal")) genresNamesList.add("gothic metal");
        if(!genresNamesList.contains("dark metal")) genresNamesList.add("dark metal");
    }

}
